### ISSUE TITLE
Disconnection from upstream

### ISSUE THREAD

**Issue by basilelt** [lflare/mdathome-golang#12]
When high or medium p2p network load (which also bump a bit CPU and RAM usage) the client get disconnected from upstream, serving chapters already cached is no issue but the non cached ones fail. The only solution to get the connection back to upstream is to restart the client. Also this issue does not happen in v1.8.1 only 1.9.1 (didn't test 1.9).

On the image, the moment fail rate explode correspond to a plex stream starting (locally, but also does it when outside local network), after that some requests went through when it was cached but download rate from upstream was 0. This correspond to February 14th 2021 between 17:15 and 19:00 UTC+1 on node #215.
[Images](https://imgur.com/a/zrSytBS)

**Comment by lflare** [comment]
Thanks for the issue report, unfortunately I don't have the time to investigate this cleanly, so I'll have to wait to see if said problem resolves itself, or someone can also encounter the same problem and report back.
