### ISSUE TITLE
Support for X-Forwarded-For and X-Real-IP header

### ISSUE THREAD

**Issue by Steamarino** [lflare/mdathome-golang#17]
It would be good to support the `X-Forwarded-For` and `X-Real-IP` header for the [ip-address check](https://github.com/lflare/mdathome-golang/blob/b700e35525197cdc8a3bf18657e0add2fb26b4c2/internal/mdathome/main.go#L73). That would be helpful when the client is behind a reverse proxy like the one from Nginx.

**Comment by lflare** [comment]
I will have something out by tomorrow.

**Comment by lflare** [comment]
Resolved 5 days later with v1.11.0
