### ISSUE TITLE
A problematic upstream image may be cached corrupted without safe check.

### ISSUE THREAD

**Issue by Cybernatus** [lflare/mdathome-golang#2]
An image from upstream may in rare occurrences be partially downloaded and cached cropped/corrupted in the cache, thus being distributed as it is until a hard refresh is performed. 

A safe check would be a good mechanism to implement if it doesn't impact the overall performances, providing a more reliable client.

**Comment by lflare** [comment]
Issue has been partially resolved as of v1.2.4 with the addition of checking for closed client connections resulting in half-downloaded images being saved to cache. Considerations have been made to verify image validity but as of now, I'm unsure if it's computationally too intensive to decode each image and check if it's corrupted before sending it to the visitor. Perhaps some form of compromise is needed?

**Comment by Cybernatus** [comment]
This is personally a path I'm willing to take, my current big issue lies in finding full chapters being broken and hard-refreshing them one by one is a hassle :x. Also, some pages are totally corrupted and won't even show, rendering their refreshes even harder. 
I am totally engaged to serve full CPI potential for the well-being of the client and if a fix is applied, I hope it'll also check local files previously downloaded cause I am hosting a mined cache for now ;_;. 
If there is a potential procedure needing some test, I'm up whenever you want.

**Comment by lflare** [comment]
@Cybernatus Completely understand your point of view, but I'm also curious to see whether there's even a programmatic way of detecting broken chapters. I have an idea in mind, but I'm out of time this weekend to implement and test, will try to do so next week :)

**Comment by lflare** [comment]
Some updates on this, image hashes have started to been added to the end of image URLs about a week ago from this comment, once it's more widespread, I can implement cache side image hash checking to check for corruption much easier...

**Comment by lflare** [comment]
This has been released with v1.5.2. Until a better alternative is found, I will close this issue and consider this fixed for now :)
